baseURL = 'http://veronicadeleon.de/'
languageCode = 'en-us'
title = 'Ver칩nica De Le칩n Hern치ndez'
googleAnalytics = "G-LQZ77WLF6C"

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[params]
    disableThemeToggle = true
    TocSide = "right"
    DateFormat = "2006"

[params.cover]
    responsiveImages = false
    linkFullImages = true


[params.homeInfoParams]
    Content = "I'm **Ver칩nica**, a **Product Designer** based in Berlin. I enjoy creating data-driven interfaces and combining my design skills with a bit of coding. During my career, I have also worked closely in the areas of Marketing and Growth."

[params.assets]
favicon = "/favicon.ico"
favicon16x16 = "/favicon-16x16.png"
favicon32x32 = "/favicon-32x32.png"
apple_touch_icon = "/apple-touch-icon.png"

[menu]

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 1

[[menu.main]]
name = "Stack"
url = "/stack/"
weight = 2

[[menu.main]]
name = "About"
url = "/about/"
weight = 3

[[menu.main]]
name = "Get in touch"
url = "/contact/"
weight = 4

[[socialIcons]]
name = "instagram"
url = "<link>"