baseURL = 'http://veronicadeleon.de/'
languageCode = 'en-us'
title = 'Ver칩nica De Le칩n Hern치ndez'

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[params]
    disableThemeToggle = true
    TocSide = "right"
    DateFormat = "2006"

[params.cover]
    responsiveImages = false
    linkFullImages = true


[params.homeInfoParams]
    Content = "I'm **Ver칩nica**, a **Product Designer** based in Berlin. I have focused my career on creating functional mobile apps and websites, combining design skills with technical knowledge."

[params.assets]
favicon = "/favicon.ico"
favicon16x16 = "/favicon-16x16.png"
favicon32x32 = "/favicon-32x32.png"
apple_touch_icon = "/apple-touch-icon.png"

[menu]

[[menu.main]]
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 2

[[menu.main]]
name = "Stack"
url = "/stack/"
weight = 3

[[menu.main]]
name = "Get in touch"
url = "/contact/"
weight = 4

[[socialIcons]]
name = "instagram"
url = "<link>"